verbatimtex \input opmac
\fontfam [LModern]
\parskip=10pt
\parindent=0pt
\hsize=255.11805000000001pt
 etex
btex \vbox{Let~$ABC$ be a~triangle. Let~$D$ be the projection of~$A$ on~$BC$. Let~$E$ be the projection of~$B$ on~$AC$. Let~$F$ be the projection of~$C$ on~$AB$. Let~$G$ be the circumcenter of~$AEF$. \par Show that points~$D,E,F,G$ are concyclic. \par\noindent\medskip \tabskip=0pt\halign to \hsize{\tabskip0pt plus1fil\hfil#\hfil&\tabskip0pt plus1fil\hfil#\hfil&\tabskip0pt plus1fil\hfil#\hfil&\tabskip0pt\hfil#\hfil\cr Type&Ranking&Weight&Contribution\cr \noalign{\vskip2pt\hrule\vskip3pt}Symmetry&$0.33$&$10000$&$3333.33$\cr Level&$0.88$&$1000$&$884.62$\cr Number of theorems&$28$&$-1$&$-28$\cr Cyclic quadrilaterals&$3$&$-10$&$-30$\cr }\par\medskip Total ranking: $4159.95$} etex
