<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>true</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>PlanarGeometryStudio</AssemblyName>
		<RootNamespace>GeoGen.DesktopApp</RootNamespace>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<VersionPrefix>1.1.1</VersionPrefix>
		<AssemblyVersion>1.1.1.0</AssemblyVersion>
		<FileVersion>1.1.1.0</FileVersion>
		<Authors>Nikola Veselinov</Authors>
		<Description>A desktop application for generating, proving, ranking, and drawing planar geometry theorems.</Description>
		<RepositoryUrl>https://github.com/nikolaveselinov/Planar-Geometry-Studio</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Include="Avalonia.Themes.Fluent" />
		<PackageReference Include="Avalonia.Fonts.Inter" />
	</ItemGroup>

</Project>
